# ==================================================================
# module list
# ------------------------------------------------------------------
# flashlight       master       (git, CPU backend)
# ==================================================================

FROM wav2letter/wav2letter:cpu-base-latest

RUN mkdir /root/wav2letter
COPY . /root/wav2letter

# ==================================================================
# flashlight https://github.com/facebookresearch/flashlight.git
# ------------------------------------------------------------------
RUN export MKLROOT=/opt/intel/mkl && \
    cd /root && git clone --recursive https://github.com/facebookresearch/flashlight.git && \
    cd flashlight && git checkout v0.2 && mkdir -p build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DFLASHLIGHT_BACKEND=CPU && \
    make -j$(nproc) && make install && \
# ==================================================================
# wav2letter with CPU backend
# ------------------------------------------------------------------
    export KENLM_ROOT_DIR=/root/kenlm && \
    cd /root/wav2letter && mkdir -p build && \
    cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DW2L_LIBRARIES_USE_CUDA=OFF && \
    make -j$(nproc)
