name: Publish CUDA Docker images
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cuda_image_build:
    name: CUDA image build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        image: wav2letter/wav2letter
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile-CUDA-test
        snapshot: true 
        tag: "tata-cuda-latest"
  cpu_image_build:
    name: CPU image build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: mr-smithers-excellent/docker-build-push@v1.0
      with:
        image: wav2letter/wav2letter
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile-CPU-test
        snapshot: true 
        tag: "tata-cpu-latest"
